# ---- SWAGGER ----
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: alpha
    use-root-path: true
    with-credentials: true
    tags-sorter: method

  show-actuator: false
  group-configs:
    # category
    - group: categories
      paths-to-match: /categories/**
      display-name: Categories
    # group
    - group: groups
      paths-to-match: /groups/**
      display-name: Groups
    # history
    - group: register
      paths-to-match:
        - /resources/consumables/registers/**
        - /resources/tools/registers/**
      display-name:
    - group: maintenance
      paths-to-match: /maintenance/**
      display-name: Maintenance
    # location
    - group: locations
      paths-to-match: /locations/**
      display-name: Locations
    # resources
    - group: consumables
      paths-to-match: /resources/consumables/**
      paths-to-exclude:
        - /resources/consumables/registers/**
        - /resources/import/**
      display-name: Consumables
    - group: upload
      paths-to-match: /resources/upload/**
      display-name: Upload
    - group: tools
      paths-to-match: /resources/tools/**
      paths-to-exclude:
        - /resources/tools/registers/**
        - /resources/import/**
      display-name: Tools
    # search
    - group: search
      paths-to-match: /search/**
      display-name: Search
    # testing
    - group: testing
      paths-to-match:
      - /test/**
      - /alive
      display-name: Testing
    # users
    - group: accounts-eula
      paths-to-match:
        - /accounts/**
        - /eula/**
      display-name: Accounts+EULA
    - group: users-volunteers
      paths-to-match:
        - /users/**
        - /volunteers/**
      display-name: Users+Volunteers
    - group: availabilities
      paths-to-match: /availability/**
      display-name: Availability
    - group: absences
      paths-to-match: /absences/**
      display-name: Absences
  show-login-endpoint: true
  enable-spring-security: true
  api-docs:
    path: /swagger/api-docs
  override-with-generic-response: false
