messages:
  info:
    USER_REGISTERED: "User registered successfully!"
    LOGOUT_SUCCESSFUL: "Logout successful"

  app:
    CREDENTIALS_EMAIL_TEMPLATE: "credentialsTemplate.html"

  errors:
    USER_NOT_FOUND: "User not found"

    VOLUNTEER_ALREADY_EXIST: "There's a volunteer with this id"

    ENDPOINT_NOT_IMPLEMENTED: "This endpoint is not implemented yet"
