#exempted endpoints from processing the token filter
exempted:
  GET:
    - "/api/eula"
  POST:
  PUT:
    - "/api/eula"
  PATCH:
  DELETE:

#endpoints that don't need/nor return token in headers
nonToken:
  GET:
    - "/api/alive"
    - "/api/accounts/validate"
  POST:
    - "/api/accounts/logout"
    - "/api/accounts/recover"
    - "/api/accounts/new-credentials"
  PUT:
  PATCH:
  DELETE:
