#exempted endpoints from processing the token filter
exempted:
  GET:
    - "/api/eula"
  POST:
    - "/api/accounts/logout"
    - "/api/refresh-token"
  PUT:
    - "/api/eula"
  PATCH:
  DELETE:

#endpoints which doesn't need token in headers
nonToken:
  GET:
    - "/api/alive"
    - "/api/accounts/validate"
  POST:
    - "/api/accounts/recover"
    - "/api/accounts/new-credentials"
  PUT:
  PATCH:
  DELETE:

#replace token endpoints to return a new token when calling these endpoints
replaceToken:
  GET:
  POST:
  PUT:
    - "/api/users/me"
    - "/api/users/{userId}"
  PATCH:
  DELETE:
