# ---- SWAGGER ----
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: alpha
    use-root-path: true
    with-credentials: true
    tags-sorter: method

  show-actuator: false
  group-configs:
    - group: testing
      paths-to-match: /test/**
      display-name: Testing
  show-login-endpoint: true
  enable-spring-security: true
  api-docs:
    path: /swagger/api-docs
  override-with-generic-response: false
