# ---- DB ----
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    # DB_HOST:
    # 'localhost' for backend unlinked in docker-compose
    # 'db' for backend linked in docker-compose
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:mydb}
    username: ${DB_USER:myuser}
    password: ${DB_PASS:mypassword}
