# ---- DB ----
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    # DB_HOST:
    # 'localhost' for backend unlinked in docker-compose
    # 'db' for backend linked in docker-compose
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME:mydb}
    username: ${DB_USER:myuser}
    password: ${DB_PASS:mypassword}
eula-standard: "https://docs.google.com/document/d/e/2PACX-1vTMAT1BQXKqh0zNooCJPFCWHYP7lXUGXdVemuGbZt9DgkZIoVoBwLPnx7DBzjwyJ0LxCpNfRKUA3nfl/pub?embedded=true"
eula-managers: "https://docs.google.com/document/d/e/2PACX-1vSXbZBtWjquXaJr9Spx7_LD9KNWg7t4G3Kxc7iGk4ZDZEhl5jVfO11ijCEAnoQY9RCN9lQqo5J6KBz4/pub?embedded=true"
