application:
  title: '@project.artifactId@'
  version: '@project.version@'
  url: '@project.url@'

spring:
  # ---- PROFILE ----
  profiles:
    include:
      - swagger
      - endpoints
      - ${ENVIRONMENT_PROFILE:dev}

  security:
    crypto:
      password:
        argon2:
          iterations: ${ARGON_ITERATIONS:16}
          memory: ${ARGON_MEMORY:128}
          parallelism: ${ARGON_THREADS:2}
          salt-length: ${ARGON_SALT_LENGTH:16}
          hash-length: ${ARGON_HASH_LENGTH:64}

  # ---- LOGGING ----
  output:
    ansi:
      enabled: ALWAYS

  # ---- MAIL ----
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_SMTP_PORT:1026}
    username: ${MAIL_USER:admin}
    password: ${MAIL_PASS:mypass}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 20000
          starttls:
            enable: ${MAIL_TLS_ENABLED:false}
            required: ${MAIL_TLS_REQUIRED:false}
          timeout: 5000
          writetimeout: 5000

  # ---- API ----
  mvc:
    servlet:
      path: /api

  # ---- DB ----
  jpa:
    open-in-view: false
    hibernate:
      # DB_START_MODE
      # create: create only when starts, destroying previous data
      # create-drop: create when starts, destroy at the end
      # update: update just the schema
      ddl-auto: ${DB_START_MODE:none}
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: ${SHOW_SQL:false} # true for format the queries (requires show_sql to true)
        show_sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true # load schema from entities
    show-sql: false # show sql queries formatted (true for formatted, requires spring.jpa.properties.hibernate.show_sql and spring.jpa.properties.hibernate.format_sql)


# ---- SERVER ----
server:
  port: ${TOMCAT_PORT:8080}
  tomcat:
    connection-timeout: ${TIMEOUT_REQUESTS:30000}
  servlet:
    encoding:
      charset: UTF-8
      force: true

# ---- JWT ----
jwtExpirationMs: ${JWT_EXPIRATION:86400}

# LOGGING
# -----------------------
logging:
  level:
    root: ${LOGGING_ROOT:INFO}
    org.springframework.web: ${LOGGING_SPRING_WEB:INFO}
    org.springframework.boot.autoconfigure.logging: ${LOGGING_SPRING_BOOT:INFO}
    org.ldcgc.backend: ${LOGGING_API:INFO}
    org.hibernate.SQL: ${LOGGING_HIBERNATE:ERROR}
    org.hibernate.type.descriptor.sql: ${LOGGING_HIBERNATE:ERROR}
    org.hibernate.orm.jdbc.bind: ${LOGGING_HIBERNATE:ERROR}
    org.junit.jupiter.api: ${LOGGING_TESTS:ERROR}
    uk.co.jemos.podam: ${LOGGING_TESTS:ERROR}
